---
- name: install virtualization packages
  become: yes
  dnf:
    name:
      - libvirt
      - qemu-kvm
      - openvswitch
      - python3-libvirt
      - python3-lxml
      - virt-install

- name: start virtualization services
  become: yes
  systemd:
    name: libvirtd
    state: started
    enabled: yes
