---
- name: install virtualization packages
  become: yes
  dnf:
    name:
      - libvirt
      - qemu-kvm
      - python3-libvirt
      - python3-lxml
      - virt-install
    state: present

- name: add user to libvirt group
  become: yes
  user:
    name: akdev
    groups: libvirt
    append: yes

- name: start virtualization services
  become: yes
  systemd:
    name: libvirtd
    state: started
    enabled: yes
